from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Protocol
from .records import EvidenceRecord, MemoryRecord, RepositoryRecord

if TYPE_CHECKING:
    from ..providers.webhooks import IngestionJob


class Storage(Protocol):
    def save_repository(self, tenant_id: str, repository: RepositoryRecord) -> None: ...
    def delete_repository(self, tenant_id: str, repository_id: str) -> bool: ...
    def get_repository(self, tenant_id: str, repository_id: str) -> RepositoryRecord | None: ...
    def list_repositories(self, tenant_id: str) -> list[RepositoryRecord]: ...
    def save_evidence(self, tenant_id: str, evidence: EvidenceRecord) -> None: ...
    def delete_evidence_except_commit(self, tenant_id: str, repository_id: str, commit: str) -> None: ...
    def list_evidence(self, tenant_id: str, repository_id: str) -> list[EvidenceRecord]: ...
    def save_memory(self, tenant_id: str, memory: MemoryRecord) -> None: ...
    def list_memories(self, tenant_id: str, repository_id: str) -> list[MemoryRecord]: ...
    def enqueue_ingestion_job(self, job: IngestionJob) -> bool: ...
    def claim_ingestion_job(self) -> IngestionJob | None: ...
    def complete_ingestion_job(self, delivery_id: str, repository_id: str) -> None: ...
    def fail_ingestion_job(self, delivery_id: str, repository_id: str) -> None: ...
    def ingestion_job_status(self) -> dict[str, int]: ...


__all__ = ["EvidenceRecord", "MemoryRecord", "RepositoryRecord", "Storage"]
