from datetime import datetime
from typing import Protocol
from .records import EvidenceRecord, MemoryRecord, RepositoryRecord


class Storage(Protocol):
    def save_repository(self, tenant_id: str, repository: RepositoryRecord) -> None: ...
    def delete_repository(self, tenant_id: str, repository_id: str) -> bool: ...
    def get_repository(self, tenant_id: str, repository_id: str) -> RepositoryRecord | None: ...
    def list_repositories(self, tenant_id: str) -> list[RepositoryRecord]: ...
    def save_evidence(self, tenant_id: str, evidence: EvidenceRecord) -> None: ...
    def list_evidence(self, tenant_id: str, repository_id: str) -> list[EvidenceRecord]: ...
    def save_memory(self, tenant_id: str, memory: MemoryRecord) -> None: ...
    def list_memories(self, tenant_id: str, repository_id: str) -> list[MemoryRecord]: ...


__all__ = ["EvidenceRecord", "MemoryRecord", "RepositoryRecord", "Storage"]
